spring:
  datasource:
    url: jdbc:mysql://10.10.47.48:3306/testdb?useUnicode=true&characterEncoding=UTF-8
    driverclassname: com.mysql.cj.jdbc.Driver
    username: testdb
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
