spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.10.47.48:3306/testdb?characterEncoding=utf8
    username: testdb
    password: 123456
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
