spring:
  datasource:
    url: jdbc:mysql://10.10.47.48:3306/testdb?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: testdb
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
